spring:
    datasource:
        url: jdbc:mysql://localhost:3306/doctracker
        username: root
        password: 1234
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
#    security:
#        user:
#            name: admin
#            password: admin123

minio:
    url: http://localhost:9002
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: documents

server:
    port: 8080