spring:
    datasource:
        url: jdbc:mysql://localhost:3306/doctracker
        username: root
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

minio:
    url: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: documents

server:
    port: 8080